In [1]:
import numpy as np
call = 15



add = []
nm = 0

while call > nm:
    lit = []
    n = 0

    while call > n:
        try:
            n += 1
            lit.append(n)
            add.append(lit)
            nm += 1
        except:
            break
    
    n = 0
   


p1 = np.array(add)
p1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7

# 첫번째 조각

In [2]:
# for i in range(5):
#     print((i+1)* "*")

for i in range(7):
  for j in range(i+1):
    p1[i][j] = 0

for p in range(7,15):
  for q in range(15-p):
    p1[p][q] = 0


print(p1)

[[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  0  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


# 두번째 조각

In [3]:
call = 15



add = []
nm = 0

while call > nm:
    lit = []
    n = 0

    while call > n:
        try:
            n += 1
            lit.append(n)
            add.append(lit)
            nm += 1
        except:
            break
    
    n = 0
   


p2 = np.array(add)
p2



for i in range(8):
  for j in range(i+1):
    p2[j][i] = 0

for p in range(7,15):
  for q in range(15 - p):
    p2[q][p] = 0

print(p2)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0 15]
 [ 1  2  0  0  0  0  0  0  0  0  0  0  0 14 15]
 [ 1  2  3  0  0  0  0  0  0  0  0  0 13 14 15]
 [ 1  2  3  4  0  0  0  0  0  0  0 12 13 14 15]
 [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]
 [ 1  2  3  4  5  6  0  0  0 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  0  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


#### 세번째 조각

In [4]:
import numpy as np
call = 15



add = []
nm = 0

while call > nm:
    lit = []
    n = 0

    while call > n:
        try:
            n += 1
            lit.append(n)
            add.append(lit)
            nm += 1
        except:
            break
    
    n = 0
   


pi3 = np.array(add)






for i in range(7):
    for j in range(14-i,15):
        pi3[i][j] = 0


for p in range(7,15): #아래 조각 완성
    for q in range(p,15):
      pi3[p][q] = 0
      # print(p)

print(pi3)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14  0]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13  0  0]
 [ 1  2  3  4  5  6  7  8  9 10 11 12  0  0  0]
 [ 1  2  3  4  5  6  7  8  9 10 11  0  0  0  0]
 [ 1  2  3  4  5  6  7  8  9 10  0  0  0  0  0]
 [ 1  2  3  4  5  6  7  8  9  0  0  0  0  0  0]
 [ 1  2  3  4  5  6  7  8  0  0  0  0  0  0  0]
 [ 1  2  3  4  5  6  7  0  0  0  0  0  0  0  0]
 [ 1  2  3  4  5  6  7  8  0  0  0  0  0  0  0]
 [ 1  2  3  4  5  6  7  8  9  0  0  0  0  0  0]
 [ 1  2  3  4  5  6  7  8  9 10  0  0  0  0  0]
 [ 1  2  3  4  5  6  7  8  9 10 11  0  0  0  0]
 [ 1  2  3  4  5  6  7  8  9 10 11 12  0  0  0]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13  0  0]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14  0]]


#### 네번째 조각

In [1]:
import numpy as np
call = 15



add = []
nm = 0

while call > nm:
    lit = []
    n = 0

    while call > n:
        try:
            n += 1
            lit.append(n)
            add.append(lit)
            nm += 1
        except:
            break
    
    n = 0
   


pi4 = np.array(add)

for i in range(7):
    for j in range(14-i,15):
        pi4[j][i] = 0


for p in range(7,15): #아래 조각 완성
    for q in range(p,15):
      pi4[q][p] = 0

print(pi4)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  7  0  9 10 11 12 13 14 15]
 [ 1  2  3  4  5  6  0  0  0 10 11 12 13 14 15]
 [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]
 [ 1  2  3  4  0  0  0  0  0  0  0 12 13 14 15]
 [ 1  2  3  0  0  0  0  0  0  0  0  0 13 14 15]
 [ 1  2  0  0  0  0  0  0  0  0  0  0  0 14 15]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
